# Generated by Django 4.2.20 on 2026-03-12 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_server', '0003_folder_flashcard_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CardSRSState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('stage', models.PositiveIntegerField(default=0)),
                ('interval_days', models.PositiveIntegerField(default=1)),
                ('due_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('last_review', models.DateTimeField(blank=True, null=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='srs_state', to='app_server.flashcard')),
            ],
            options={
                'db_table': 'card_srs_states',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='CardReviewLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('choice', models.CharField(choices=[('EASY', 'Easy'), ('GOOD', 'Good'), ('HARD', 'Hard')], max_length=4)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('prev_stage', models.PositiveIntegerField()),
                ('new_stage', models.PositiveIntegerField()),
                ('prev_interval', models.PositiveIntegerField()),
                ('new_interval', models.PositiveIntegerField()),
                ('prev_due_date', models.DateField()),
                ('new_due_date', models.DateField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='app_server.flashcard')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='srs.reviewsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_review_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'card_review_logs',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reviewsession',
            index=models.Index(fields=['user', 'started_at'], name='idx_review_session_user_start'),
        ),
        migrations.AddIndex(
            model_name='cardsrsstate',
            index=models.Index(fields=['due_date'], name='idx_srs_due_date'),
        ),
        migrations.AddIndex(
            model_name='cardreviewlog',
            index=models.Index(fields=['user', 'reviewed_at'], name='idx_review_log_user_date'),
        ),
    ]
