# Generated by Django 4.2.20 on 2026-03-23
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('srs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsession',
            name='folder',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='review_sessions',
                to='app_server.folder',
            ),
        ),
    ]

