# Generated by Django 4.2.20 on 2026-03-12 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0002_course_module_lesson_lessonprogress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'folders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('front_text', models.TextField()),
                ('back_text', models.TextField()),
                ('ipa', models.CharField(blank=True, default='', max_length=255)),
                ('audio_url', models.URLField(blank=True, default='', max_length=500)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('card_type', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('phrase', 'Phrase'), ('sentence', 'Sentence')], default='vocabulary', max_length=20)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='app_server.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flashcards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('user', 'name'), name='unique_active_folder_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['user', 'folder'], name='idx_flashcard_user_folder'),
        ),
    ]
