# Generated by Django 4.2.20 on 2026-03-12 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0003_folder_flashcard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('xp_amount', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('lesson', 'Lesson'), ('review', 'Review'), ('quiz', 'Quiz'), ('speaking', 'Speaking')], max_length=20)),
                ('source_id', models.UUIDField(blank=True, help_text='ID of the related entity', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'xp_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserXP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('weekly_xp', models.PositiveIntegerField(default=0)),
                ('monthly_xp', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xp_summary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_xp',
                'ordering': ['-total_xp'],
            },
        ),
    ]
