# Generated by Django 4.2.20 on 2026-03-12 04:36

import apps.app_server.models.user_model
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0004_xptransaction_userxp'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.app_server.models.user_model.SoftDeleteUserManager()),
            ],
        ),
    ]
