# Generated by Django 4.2.20 on 2026-03-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_markdown',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('quiz', 'Quiz')], default='video', max_length=10),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(condition=models.Q(('is_final', True)), fields=('module',), name='unique_final_lesson_per_module'),
        ),
    ]
