# Generated by Django 4.2.20 on 2026-03-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0006_lesson_content_markdown_lesson_is_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='quiz_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='quiz_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='quiz_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='quiz_total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
