# Generated by Django 4.2.20 on 2026-03-19 09:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_server', '0008_lessonprogress_quiz_hearts_left_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonIngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('job_type', models.CharField(choices=[('ingest', 'Ingest'), ('reingest', 'Reingest'), ('delete_index', 'Delete Index')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('trigger_source', models.CharField(choices=[('lesson_created', 'Lesson Created'), ('lesson_updated', 'Lesson Updated'), ('manual_reindex', 'Manual Reindex'), ('lesson_deleted', 'Lesson Deleted')], max_length=20)),
                ('source_version', models.CharField(blank=True, default='', max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('error_payload', models.JSONField(blank=True, default=dict)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='app_server.lesson')),
            ],
            options={
                'db_table': 'lesson_ingestion_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonSourceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('source_type', models.CharField(choices=[('text_markdown', 'Text Markdown'), ('video_url_transcript', 'Video URL Transcript')], max_length=32)),
                ('source_locator', models.CharField(blank=True, default='', max_length=500)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('normalized_text', models.TextField(blank=True, default='')),
                ('language_code', models.CharField(blank=True, default='', max_length=16)),
                ('checksum', models.CharField(blank=True, default='', max_length=128)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('ingestion_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to='lesson_ingestion.lessoningestionjob')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to='app_server.lesson')),
            ],
            options={
                'db_table': 'lesson_source_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonContentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('token_estimate', models.PositiveIntegerField(default=0)),
                ('char_start', models.PositiveIntegerField(default=0)),
                ('char_end', models.PositiveIntegerField(default=0)),
                ('vector_document_id', models.CharField(blank=True, default='', max_length=255)),
                ('embedding_provider', models.CharField(blank=True, default='', max_length=100)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=255)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('ingestion_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_chunks', to='lesson_ingestion.lessoningestionjob')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_chunks', to='app_server.lesson')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_chunks', to='lesson_ingestion.lessonsourcedocument')),
            ],
            options={
                'db_table': 'lesson_content_chunks',
                'ordering': ['chunk_index', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lessonsourcedocument',
            index=models.Index(fields=['lesson', 'source_type'], name='idx_source_doc_lesson_type'),
        ),
        migrations.AddIndex(
            model_name='lessonsourcedocument',
            index=models.Index(fields=['checksum'], name='idx_source_doc_checksum'),
        ),
        migrations.AddIndex(
            model_name='lessoningestionjob',
            index=models.Index(fields=['lesson', 'status'], name='idx_ingest_job_lesson_status'),
        ),
        migrations.AddIndex(
            model_name='lessoningestionjob',
            index=models.Index(fields=['status', 'created_at'], name='idx_ingest_job_status_created'),
        ),
        migrations.AddIndex(
            model_name='lessoncontentchunk',
            index=models.Index(fields=['lesson', 'is_active'], name='idx_chunk_lesson_active'),
        ),
        migrations.AddIndex(
            model_name='lessoncontentchunk',
            index=models.Index(fields=['vector_document_id'], name='idx_chunk_vector_doc'),
        ),
        migrations.AddConstraint(
            model_name='lessoncontentchunk',
            constraint=models.UniqueConstraint(fields=('source_document', 'chunk_index'), name='uniq_chunk_source_index'),
        ),
    ]
